"""Evaluates the trained ML detector against a held-out labelled dataset
that was never touched during training or hyperparameter/model-family
selection (see ml_engine.train's SEED_EVAL).

Run directly to (re)compute metrics and refresh EVALUATION.md:

    python -m ml_engine.evaluate
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List

import numpy as np
from sklearn.metrics import confusion_matrix, f1_score, precision_score, recall_score, roc_auc_score

from ml_engine.detector import load_model, predict
from ml_engine.train import N_EVAL_PER_PROFILE, SEED_EVAL, WINDOW_SECONDS
from ml_engine.traffic_profiles import ALL_PROFILES, ATTACK_PROFILES, NORMAL_PROFILES, build_feature_dataset

EVALUATION_MD_PATH = Path(__file__).parent.parent / "EVALUATION.md"


def build_eval_set():
    """The held-out evaluation set: a seed never used in training or
    validation (ml_engine.train.SEED_TRAIN / SEED_VAL)."""
    all_names = list(ALL_PROFILES.keys())
    X, labels, scenarios = build_feature_dataset(all_names, N_EVAL_PER_PROFILE, SEED_EVAL, WINDOW_SECONDS)
    y_true = np.array([1 if label == "attack" else 0 for label in labels])  # 1 = attack (positive class)
    return X, y_true, np.array(scenarios)


def evaluate_model(model_artifact: Dict[str, Any], X: np.ndarray, y_true: np.ndarray, scenarios: np.ndarray) -> Dict[str, Any]:
    n = X.shape[0]
    y_pred = np.zeros(n, dtype=int)
    scores = np.zeros(n, dtype=float)
    for i in range(n):
        result = predict(X[i], model_artifact)
        y_pred[i] = 1 if result["status"] == "ANOMALY" else 0
        scores[i] = result["anomaly_score"]

    is_normal = y_true == 0
    is_attack = y_true == 1

    fpr = float(np.mean(y_pred[is_normal] == 1)) if is_normal.any() else float("nan")
    overall_recall = float(np.mean(y_pred[is_attack] == 1)) if is_attack.any() else float("nan")
    precision = precision_score(y_true, y_pred, pos_label=1, zero_division=0)
    f1 = f1_score(y_true, y_pred, pos_label=1, zero_division=0)
    # Higher score = more normal (sklearn decision_function convention), so
    # more-anomalous-is-higher (what roc_auc_score wants for the positive
    # class = attack) is -scores.
    roc_auc = roc_auc_score(y_true, -scores) if is_normal.any() and is_attack.any() else float("nan")
    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])

    per_scenario: Dict[str, Dict[str, Any]] = {}
    per_scenario_mean_score: Dict[str, float] = {}
    for scenario in sorted(set(scenarios)):
        mask = scenarios == scenario
        label = "normal" if scenario in NORMAL_PROFILES else "attack"
        detected_as_anomaly = float(np.mean(y_pred[mask] == 1))
        per_scenario[scenario] = {
            "label": label,
            "n": int(mask.sum()),
            "fpr_or_recall": detected_as_anomaly,
        }
        per_scenario_mean_score[scenario] = float(np.mean(scores[mask]))

    return {
        "n_samples": n,
        "n_normal": int(is_normal.sum()),
        "n_attack": int(is_attack.sum()),
        "fpr": fpr,
        "recall": overall_recall,
        "precision": float(precision),
        "f1": float(f1),
        "roc_auc": float(roc_auc),
        "confusion_matrix": cm.tolist(),
        "per_scenario": per_scenario,
        "per_scenario_mean_score": per_scenario_mean_score,
    }


def _write_evaluation_md(model_artifact: Dict[str, Any], metrics: Dict[str, Any], path: Path = EVALUATION_MD_PATH) -> None:
    lines: List[str] = []
    lines.append("# ML Detector Evaluation\n")
    lines.append(
        "Auto-generated by `python -m ml_engine.evaluate`. Do not hand-edit the "
        "numbers below -- rerun the command instead, so this file always reflects "
        "what the shipped model actually measures.\n"
    )

    lines.append("## Dataset provenance\n")
    lines.append(
        "All training and evaluation data is **synthetic**, generated by "
        "`ml_engine.traffic_profiles`. Real public datasets were checked first "
        "and found impractical in this environment:\n"
    )
    lines.append(
        "- **MAWI** (https://mawi.wide.ad.jp/mawi/): daily samples are ~1.85GB "
        "each and carry no attack ground-truth labels (it's raw, mostly-unlabelled "
        "backbone traffic) -- unusable for a labelled recall/FPR evaluation without "
        "a separate, substantial labelling effort.\n"
    )
    lines.append(
        "- **CIC-IDS2017** (https://www.unb.ca/cic/datasets/ids-2017.html): the "
        "PCAP directory redirects to a dataset request/index page rather than "
        "offering direct file downloads.\n"
    )
    lines.append(
        "- **UNSW-NB15**: not attempted directly given the above; similarly "
        "hosted as large archives typically requiring a request process.\n"
    )
    lines.append(
        "\nIf you have access to one of these (or another labelled capture set) "
        "and want to substitute it in, the integration point is "
        "`ml_engine.evaluate.build_eval_set()` -- replace it with a loader that "
        "reads real packets through `core.sniffer.read_pcap` and labels windows "
        "from the dataset's ground truth, then run the extractor over them exactly "
        "as `ml_engine.traffic_profiles.build_feature_dataset` does.\n"
    )

    provenance = model_artifact.get("training_provenance", {})
    lines.append("\n### Splits and seeds\n")
    lines.append("| Split | Seed | Windows/profile | Purpose |")
    lines.append("|---|---|---|---|")
    lines.append(f"| Train | {provenance.get('seed_train')} | {provenance.get('n_train_per_profile')} | Fit the model (normal-only) |")
    lines.append(f"| Validation | {provenance.get('seed_val')} | {provenance.get('n_val_per_profile')} | Hyperparameter/model-family selection |")
    lines.append(f"| Evaluation (held out) | {SEED_EVAL} | {N_EVAL_PER_PROFILE} | This report -- never touched during training/tuning |")
    lines.append(f"\nWindow size: {provenance.get('window_seconds')}s.\n")

    lines.append("## Model\n")
    lines.append(f"- **Family**: {model_artifact.get('model_family')}")
    lines.append(f"- **Hyperparameters**: `{model_artifact.get('hyperparameters')}`")
    lines.append(f"- **Preprocessing**: log1p on heavy-tailed count/rate features, then RobustScaler (see ml_engine/preprocessing.py)")
    lines.append(f"- **Validation metrics at selection time**: `{model_artifact.get('validation_metrics')}`\n")

    lines.append("## Held-out evaluation results\n")
    lines.append(f"n = {metrics['n_samples']} ({metrics['n_normal']} normal, {metrics['n_attack']} attack)\n")
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    lines.append(f"| False Positive Rate | {metrics['fpr']:.3f} |")
    lines.append(f"| Recall (overall, attack) | {metrics['recall']:.3f} |")
    lines.append(f"| Precision | {metrics['precision']:.3f} |")
    lines.append(f"| F1 | {metrics['f1']:.3f} |")
    lines.append(f"| ROC-AUC | {metrics['roc_auc']:.3f} |")

    cm = metrics["confusion_matrix"]
    lines.append("\n**Confusion matrix** (rows = true, cols = predicted; order [normal, attack]):\n")
    lines.append("```")
    lines.append(f"              pred_normal  pred_attack")
    lines.append(f"true_normal   {cm[0][0]:>11}  {cm[0][1]:>11}")
    lines.append(f"true_attack   {cm[1][0]:>11}  {cm[1][1]:>11}")
    lines.append("```\n")

    lines.append("### Per-scenario breakdown\n")
    lines.append("| Scenario | Label | n | Detected-as-anomaly rate | Mean anomaly score |")
    lines.append("|---|---|---|---|---|")
    for scenario, info in sorted(metrics["per_scenario"].items()):
        rate_name = "FPR" if info["label"] == "normal" else "Recall"
        lines.append(
            f"| {scenario} | {info['label']} | {info['n']} | {rate_name}={info['fpr_or_recall']:.3f} | "
            f"{metrics['per_scenario_mean_score'][scenario]:.4f} |"
        )

    lines.append(
        "\nNote: a *lower* mean anomaly score means the model considers those "
        "windows *more* anomalous. Every attack scenario's mean score should be "
        "lower than every normal scenario's mean score -- see tests/test_ml_quality.py's "
        "ranking-sanity gate."
    )

    lines.append("\n## Iteration history\n")
    lines.append(
        "Kept here (regenerated each run, not overwritten) because the numbers "
        "above alone don't explain *why* the model looks the way it does. Two "
        "methodology bugs were found and fixed by looking at *why* validation "
        "FPR was catastrophic for specific normal scenarios, not just tuning "
        "the model harder against the same broken features/data:\n"
    )
    lines.append(
        "1. **`dest_port_entropy` was normalized by `log2(unique_port_count)`.** "
        "This bounded it to [0, 1], but conflated \"evenly split across 2 "
        "values\" with \"evenly split across 50 values\" -- both normalized to "
        "~1.0. Real web traffic realistically only ever uses 1-2 destination "
        "ports (80/443) no matter how many sites are visited, so it scored "
        "nearly as \"scan-like\" as an actual port scan. Fixed by using raw "
        "(unnormalized) Shannon entropy in bits, so 2 ports caps at 1 bit while "
        "a 50-port scan reaches ~5.6 bits -- a real numeric gap the model can "
        "use. See core/extractor.py's `_shannon_entropy` docstring.\n"
    )
    lines.append(
        "2. **`profile_mixed_office` let each sub-traffic-type (web browsing, "
        "DNS, bulk transfer) pick its own random source IP.** A single "
        "simulated workstation doing three things at once ended up looking "
        "like 2-3 different hosts, inflating `unique_source_ip_count` in a "
        "way that doesn't happen on a real single-host workstation. Fixed by "
        "generating one source IP per mixed_office window and threading it "
        "through every sub-profile call. See "
        "`ml_engine/traffic_profiles.py`'s `profile_mixed_office` docstring.\n"
    )
    lines.append(
        "Before these two fixes, the same OneClassSVM/LocalOutlierFactor "
        "search produced an aggregate FPR that looked acceptable (~0.16-0.17) "
        "while `web_browsing` and `mixed_office` individually sat at 40-68% "
        "FPR -- exactly the failure mode `tests/test_ml_quality.py`'s "
        "per-scenario gate exists to catch. Fixing the underlying feature/data "
        "bugs (not the decision threshold) resolved it: aggregate FPR dropped "
        "to ~0.02 and every individual scenario is comfortably under the 10% "
        "per-scenario budget.\n"
    )
    lines.append(
        "One known cosmetic quirk, not a correctness issue: "
        "`LocalOutlierFactor`'s decision_function isn't bounded the way "
        "`IsolationForest`'s is, so anomaly scores for extreme windows (e.g. "
        "an ICMP flood) can be very large in magnitude (see the per-scenario "
        "table above). `ui/console.py` formats the displayed score with `.4g` "
        "rather than a fixed decimal count specifically to keep this readable; "
        "the NORMAL/ANOMALY classification itself is unaffected."
    )

    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    model_artifact = load_model()
    X, y_true, scenarios = build_eval_set()
    metrics = evaluate_model(model_artifact, X, y_true, scenarios)

    print(f"n={metrics['n_samples']} ({metrics['n_normal']} normal, {metrics['n_attack']} attack)")
    print(f"FPR={metrics['fpr']:.3f}  Recall={metrics['recall']:.3f}  "
          f"Precision={metrics['precision']:.3f}  F1={metrics['f1']:.3f}  ROC-AUC={metrics['roc_auc']:.3f}")
    print("\nPer-scenario:")
    for scenario, info in sorted(metrics["per_scenario"].items()):
        rate_name = "FPR" if info["label"] == "normal" else "Recall"
        print(f"  {scenario:<24} {info['label']:<7} n={info['n']:<4} {rate_name}={info['fpr_or_recall']:.3f} "
              f"mean_score={metrics['per_scenario_mean_score'][scenario]:.4f}")

    _write_evaluation_md(model_artifact, metrics)
    print(f"\nWrote {EVALUATION_MD_PATH}")


if __name__ == "__main__":
    main()
